# Put here anything you would like and it will be rendered as a template
# Example:
# extraDeploy:
#   - |
#     apiVersion: v1
#     kind: PersistentVolumeClaim
#     metadata:
#       name: {{ .Release.Name }}
#       namespace: {{ .Release.Namespace }}
#     ...
extraDeploy: []

## NOTE: It is important to know that subcharts (dependencies) share helper functions but can not access the parent chart values.
## If you'd like to pass values to this subchart, you will need to do it using 'global' or duplicating them under the subchart values section.
